#ifndef SCRIBE_CODES_H
#define SCRIBE_CODES_H

#include <stddef.h>

typedef enum scribe_code_e {
    SCRIBE_CODE_OK = 0,

    SCRIBE_CODE_NOT_INITIALIZED,
    SCRIBE_CODE_ALREADY_INITIALIZED,

    SCRIBE_CODE_NULL_SINKS,
    SCRIBE_CODE_INVALID_SINKS_COUNT,

    SCRIBE_CODE_NULL_SINK,
    SCRIBE_CODE_NULL_SINK_CLASS,
    SCRIBE_CODE_INTERNAL_INVALID_METHODS_OFFSETS,
    SCRIBE_CODE_NULL_SINK_CLASS_METHOD,

    SCRIBE_INVALID_DATA,

    SCRIBE_CODE_NO_DATA,
    SCRIBE_CODE_INVALID_DATA_BYTESIZE,

    SCRIBE_CODE_WRITE_FAILURE,

    SCRIBE_CODE_FIRST = SCRIBE_CODE_OK,
    SCRIBE_CODE_LAST  = SCRIBE_CODE_WRITE_FAILURE,
} scribe_code_t;

#define SCRIBE_CODE_COUNT ((size_t)( SCRIBE_CODE_LAST - SCRIBE_CODE_FIRST + 1 ))

extern const char * scribe_get_code_label(scribe_code_t code);

#endif /* SCRIBE_CODES_H */
