#ifndef SCRIBE_CODES_H
#define SCRIBE_CODES_H

#include <stddef.h>

typedef enum scribe_code_e {
    SCRIBE_CODE_OK = 0,

    SCRIBE_CODE_NOT_INITIALIZED,

    SCRIBE_CODE_ALREADY_INITIALIZED,
    SCRIBE_CODE_NO_PDU,
    SCRIBE_CODE_NO_BUFFER,
    SCRIBE_CODE_INVALID_BUFFER_BYTESIZE,
    SCRIBE_CODE_INVALID_BLOCK_NUMBER,
    SCRIBE_CODE_INITIALIZATION_FAILURE,

    SCRIBE_CODE_NO_DATA,
    SCRIBE_CODE_INVALID_DATA_BYTESIZE,
    SCRIBE_CODE_WRITE_FAILURE,

    SCRIBE_CODE_FLUSH,

    SCRIBE_CODE_FIRST = SCRIBE_CODE_OK,
    SCRIBE_CODE_LAST  = SCRIBE_CODE_FLUSH,
} scribe_code_t;

#define SCRIBE_CODE_COUNT ((size_t)( SCRIBE_CODE_LAST - SCRIBE_CODE_FIRST + 1 ))

extern const char * scribe_code_get_label(scribe_code_t code);

#endif /* SCRIBE_CODES_H */
